[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
evm_version = "prague"

[dependencies]
forge-std = "1.10.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
